POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Sample Product this",
  "description": "This is a sample product for testing.",
  "price": 30.99,
  "category": "electronics",
  "stock": 1000
}